distributable:
  # Actual version number does not comply with semantic versioning
  url: https://www.chiark.greenend.org.uk/~sgtatham/puzzles/puzzles.tar.gz
  strip-components: 1

display-name: puzzles

versions:
  url: https://www.chiark.greenend.org.uk/~sgtatham/puzzles/doc/
  match: /\d+\.[\da-f]{7}/
  strip:
    - /\.[\da-f]{7}$/

dependencies:
  linux:
    gtk.org/gtk3: '*'

build:
  dependencies:
    cmake.org: '>=3.5'
    chiark.greenend.org.uk/halibut: '*'
    linux:
      llvm.org: 20
      imagemagick.org: '*'
  script:
    - cmake . $ARGS
    - cmake --build . -j {{ hw.concurrency }}
    - cmake --install .
    - run: ln -s ../Puzzles.app/Contents/MacOS/Puzzles puzzles
      if: darwin
  env:
    ARGS:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX={{prefix}}

provides:
  darwin:
    - bin/puzzles
  linux:
    - bin/blackbox
    - bin/bridges
    - bin/cube
    - bin/dominosa
    - bin/fifteen
    - bin/filling
    - bin/flip
    - bin/flood
    - bin/galaxies
    - bin/guess
    - bin/inertia
    - bin/keen
    - bin/lightup
    - bin/loopy
    - bin/magnets
    - bin/map
    - bin/mines
    - bin/mosaic
    - bin/net
    - bin/netslide
    - bin/palisade
    - bin/pattern
    - bin/pearl
    - bin/pegs
    - bin/range
    - bin/rect
    - bin/samegame
    - bin/signpost
    - bin/singles
    - bin/sixteen
    - bin/slant
    - bin/solo
    - bin/tents
    - bin/towers
    - bin/tracks
    - bin/twiddle
    - bin/undead
    - bin/unequal
    - bin/unruly
    - bin/untangle

test:
  - run: map --generate
    if: linux
  - run: puzzles --help
    if: darwin
