distributable:
  url: https://ftp.gnu.org/gnu/glibc/glibc-{{ version.raw }}.tar.gz
  strip-components: 1

versions:
  #TODO HTML listing: https://ftp.gnu.org/gnu/glibc/
  - 2.28
  # - 2.33

platforms:
  linux

build:
  dependencies:
    gnu.org/make: '>=3.79'
    gnu.org/gawk: '>=3'
    gnu.org/gcc: ^13.2
    gnu.org/gettext: ~0.22.4
    gnu.org/texinfo: ^7
    gnu.org/bison: ^3
    perl.org: ^5
    python.org: ~3.11
  working-directory: build
  script:
    #FIXME
    # Putting ourselves in the LD_LIBRARY_PATH breaks literally everything else...
    - export LD_LIBRARY_PATH=/root/.pkgx/zlib.net/v1.3.0/lib:/root/.pkgx/gnome.org/libxml2/v2.12.3/lib:/root/.pkgx/tukaani.org/xz/v5.4.5/lib:/root/.pkgx/perl.org/v5.38.2/lib:/root/.pkgx/sourceware.org/bzip2/v1.0.8/lib:/root/.pkgx/openssl.org/v1.1.1w/lib:/root/.pkgx/libexpat.github.io/v2.5.0/lib:/root/.pkgx/gnu.org/gcc/v13.2.0/lib:/root/.pkgx/gnu.org/gawk/v5.3.0/lib:/root/.pkgx/sqlite.org/v3.44.2/lib:/root/.pkgx/gnu.org/texinfo/v7.1.0/lib:/root/.pkgx/x.org/exts/v1.3.5/lib:/root/.pkgx/invisible-island.net/ncurses/v6.4.0/lib:/root/.pkgx/gnu.org/bison/v3.8.2/lib:/root/.pkgx/gnu.org/gettext/v0.22.4/lib:/root/.pkgx/gnu.org/mpfr/v4.2.1/lib:/root/.pkgx/gnu.org/mpc/v1.3.1/lib:/root/.pkgx/x.org/xcb/v1.16.0/lib:/root/.pkgx/python.org/v3.11.7/lib:/root/.pkgx/x.org/x11/v1.8.7/lib:/root/.pkgx/sourceware.org/libffi/v3.4.4/lib:/root/.pkgx/libpng.org/v1.6.40/lib:/root/.pkgx/gnu.org/gmp/v6.3.0/lib:/root/.pkgx/gnu.org/readline/v8.2.0/lib:/root/.pkgx/x.org/xau/v1.0.11/lib:/root/.pkgx/bytereef.org/mpdecimal/v2.5.1/lib:/root/.pkgx/freetype.org/v2.13.2/lib:/root/.pkgx/tcl-lang.org/v8.6.13/lib:/root/.pkgx/x.org/xdmcp/v1.1.4/lib:/root/.pkgx/gnu.org/binutils/v2.41.0/lib

    - ../configure $ARGS
    - make all #-j {{hw.concurrency}}
    - make install

    - run: |
        for s in $SCRIPTS; do
          sed -i.bak 's|{{prefix}}|"$(cd "$(dirname "$0")/.." \&\& pwd)"|' $s
          rm $s.bak
        done
      working-directory: ${{prefix}}/bin

    - run: ln -s ../lib/ld-{{ version.marketing }}.so ld.so
      working-directory: ${{prefix}}/bin
  test:
    make test
  env:
    SCRIPTS:
      - catchsegv
      - ldd
      - mtrace
      - sotruss
      - tzselect
      - xtrace
    ARGS:
      - --prefix={{ prefix }}
      - --disable-debug
      - --disable-dependency-tracking
      - --disable-silent-rules
      - --disable-werror
      - --enable-obsolete-rpc
      - --without-gd
      - --without-selinux
      - --enable-kernel=2.6.0
      - --with-binutils={{deps.gnu.org/binutils.prefix}}/bin
      - --disable-multi-arch  # ChatGPT suggested
    CFLAGS: -O2 -fPIC
    CXXFLAGS: -O2 -fPIC
    LDFLAGS: -pie

test:
  dependencies:
    gnu.org/gcc: '*'
  env:
    linux/x86-64:
      ARCH: x86_64
    linux/aarch64:
      ARCH: aarch64
  script:
    # Putting ourselves in the LD_LIBRARY_PATH breaks literally everything else...
    - export LD_LIBRARY_PATH="$(echo LD_LIBRARY_PATH | tr ':' '\n' | grep -v {{prefix}} | tr '\n' ':')"

    - gcc -o test1 test.c -fPIC -pie
    - ./test1

    - |
      gcc \
        -nostdinc \
        -nostdlib \
        -I{{deps.gnu.org/gcc.prefix}}/lib/gcc/$ARCH-unknown-linux-gnu/{{deps.gnu.org/gcc.version}}/include \
        -Wl,--rpath="{{prefix}}/lib" \
        -Wl,--dynamic-linker={{prefix}}/bin/ld.so \
        -std=c11 \
        -o test2 \
        -v \
        $CFLAGS \
        {{prefix}}/lib/crti.o \
        {{prefix}}/lib/crt1.o \
        {{prefix}}/lib/crtn.o \
        test.c \
        -fPIC \
        -pie

    - test "$(./test2)" = "gnu_get_libc_version() = {{version.marketing}}"

provides:
  - bin/catchsegv
  - bin/gencat
  - bin/getconf
  - bin/getent
  - bin/iconv
  - bin/ldd
  - bin/locale
  - bin/localedef
  - bin/makedb
  - bin/mtrace
  - bin/pcprofiledump
  - bin/pldd
  - bin/sotruss
  - bin/sprof
  - bin/tzselect
  - bin/xtrace
  - sbin/iconvconfig
  - sbin/ldconfig
  - sbin/nscd
  - sbin/sln
  - sbin/zdump
  - sbin/zic